@csrf
@php
    $registration = $configuration->registration_rules ?? [];
    $qr = $configuration->qr_rules ?? [];
    $capacity = $configuration->capacity_rules ?? [];
    $email = $configuration->email_settings ?? [];
@endphp
<div class="space-y-6">
    <section class="grid gap-5 md:grid-cols-2">
        <div><label for="name" class="block text-sm font-medium text-slate-700">Configuration name</label><input id="name" name="name" value="{{ old('name', $configuration->name ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
        <label class="flex min-h-11 items-end gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="is_default" value="1" @checked(old('is_default', $configuration->is_default ?? false)) class="mb-3 rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Set as default configuration</label>
    </section>

    <fieldset class="rounded-lg border border-slate-200 p-4"><legend class="px-1 text-sm font-semibold">Registration defaults</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="registration_requires_approval" value="1" @checked(old('registration_requires_approval', $registration['requires_approval'] ?? false)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Requires approval</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="registration_allow_waitlist" value="1" @checked(old('registration_allow_waitlist', $registration['allow_waitlist'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Allow waitlist</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="registration_private_by_default" value="1" @checked(old('registration_private_by_default', $registration['private_by_default'] ?? false)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Private by default</label><div><label for="registration_open_days_before" class="block text-sm font-medium text-slate-700">Open days before event</label><input id="registration_open_days_before" name="registration_open_days_before" type="number" min="0" value="{{ old('registration_open_days_before', $registration['open_days_before'] ?? 30) }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div></div></fieldset>

    <fieldset class="rounded-lg border border-slate-200 p-4"><legend class="px-1 text-sm font-semibold">QR defaults</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="qr_enabled" value="1" @checked(old('qr_enabled', $qr['enabled'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">QR enabled</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="qr_allow_reuse" value="1" @checked(old('qr_allow_reuse', $qr['allow_reuse'] ?? false)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Allow QR reuse</label><div><label for="qr_expires_after_event_hours" class="block text-sm font-medium text-slate-700">Expiry after event hours</label><input id="qr_expires_after_event_hours" name="qr_expires_after_event_hours" type="number" min="0" value="{{ old('qr_expires_after_event_hours', $qr['expires_after_event_hours'] ?? 24) }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div></div></fieldset>

    <fieldset class="rounded-lg border border-slate-200 p-4"><legend class="px-1 text-sm font-semibold">Capacity defaults</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="capacity_enforce_limit" value="1" @checked(old('capacity_enforce_limit', $capacity['enforce_limit'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Enforce limit</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="capacity_waitlist_when_full" value="1" @checked(old('capacity_waitlist_when_full', $capacity['waitlist_when_full'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Waitlist when full</label><div><label for="capacity_overbooking_limit" class="block text-sm font-medium text-slate-700">Overbooking limit</label><input id="capacity_overbooking_limit" name="capacity_overbooking_limit" type="number" min="0" value="{{ old('capacity_overbooking_limit', $capacity['overbooking_limit'] ?? 0) }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div></div></fieldset>

    <fieldset class="rounded-lg border border-slate-200 p-4"><legend class="px-1 text-sm font-semibold">Email defaults</legend><div class="mt-3 grid gap-4 md:grid-cols-2"><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="email_send_confirmation" value="1" @checked(old('email_send_confirmation', $email['send_confirmation'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Send confirmation</label><label class="flex items-center gap-2 text-sm"><input type="checkbox" name="email_send_reminder" value="1" @checked(old('email_send_reminder', $email['send_reminder'] ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Send reminder</label><div><label for="email_reminder_hours_before" class="block text-sm font-medium text-slate-700">Reminder hours before</label><input id="email_reminder_hours_before" name="email_reminder_hours_before" type="number" min="0" value="{{ old('email_reminder_hours_before', $email['reminder_hours_before'] ?? 24) }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div></div></fieldset>
</div>
<div class="mt-6 flex gap-3"><button class="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800">{{ $button ?? 'Save configuration' }}</button><a href="{{ route('admin.event-configurations.index') }}" class="inline-flex min-h-11 items-center rounded-lg border border-slate-300 px-4 text-sm font-semibold hover:bg-slate-50">Cancel</a></div>
