@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label for="name" class="block text-sm font-medium text-slate-700">Status name</label><input id="name" name="name" value="{{ old('name', $status->name ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="key" class="block text-sm font-medium text-slate-700">Key</label><input id="key" name="key" value="{{ old('key', $status->key ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="color" class="block text-sm font-medium text-slate-700">Color token</label><input id="color" name="color" value="{{ old('color', $status->color ?? 'slate') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="sort_order" class="block text-sm font-medium text-slate-700">Sort order</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $status->sort_order ?? 0) }}" class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div class="md:col-span-2 flex flex-wrap gap-5"><label class="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $status->is_active ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Active</label><label class="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="is_terminal" value="1" @checked(old('is_terminal', $status->is_terminal ?? false)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Terminal status</label></div>
</div>
<div class="mt-6 flex gap-3"><button class="btn btn-primary btn-md">{{ $button ?? 'Save status' }}</button><a href="{{ route('admin.event-statuses.index') }}" class="btn btn-outline-primary btn-md">Cancel</a></div>
