@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label for="name" class="block text-sm font-medium text-slate-700">Venue name</label><input id="name" name="name" value="{{ old('name', $venue->name ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="code" class="block text-sm font-medium text-slate-700">Code</label><input id="code" name="code" value="{{ old('code', $venue->code ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="capacity" class="block text-sm font-medium text-slate-700">Capacity</label><input id="capacity" name="capacity" type="number" min="0" value="{{ old('capacity', $venue->capacity ?? 0) }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="status" class="block text-sm font-medium text-slate-700">Status</label><select id="status" name="status" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', isset($venue) ? $venue->status->value : 'active') === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></div>
    <div class="md:col-span-2"><label for="location" class="block text-sm font-medium text-slate-700">Location</label><input id="location" name="location" value="{{ old('location', $venue->location ?? '') }}" class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div class="md:col-span-2"><label for="description" class="block text-sm font-medium text-slate-700">Description</label><textarea id="description" name="description" rows="4" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">{{ old('description', $venue->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800">{{ $button ?? 'Save venue' }}</button><a href="{{ route('admin.venues.index') }}" class="inline-flex min-h-11 items-center rounded-lg border border-slate-300 px-4 text-sm font-semibold hover:bg-slate-50">Cancel</a></div>
