@php($event = $event ?? null)
@php($eventStatus = $event?->status_key instanceof \BackedEnum ? $event->status_key->value : ($event?->status_key ?? 'draft'))
<div class="grid gap-5 lg:grid-cols-2">
    <label class="block"><span class="text-sm font-medium">Event name</span><input name="title" value="{{ old('title', $event?->title) }}" required class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Organiser profile</span><select name="organiser_profile_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Select organiser</option>@foreach(($organiserProfiles ?? collect()) as $profile)<option value="{{ $profile->id }}" @selected(old('organiser_profile_id', $event?->organiser_profile_id) == $profile->id)>{{ $profile->name }} · {{ $profile->email }}</option>@endforeach</select></label>
    <label class="block"><span class="text-sm font-medium">Custom site URL</span><input name="custom_url" value="{{ old('custom_url', $event?->custom_url ?? $event?->slug) }}" required pattern="[a-z0-9-]+" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Start date/time</span><input type="datetime-local" name="starts_at" value="{{ old('starts_at', optional($event?->starts_at)->format('Y-m-d\TH:i')) }}" required class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">End date/time</span><input type="datetime-local" name="ends_at" value="{{ old('ends_at', optional($event?->ends_at)->format('Y-m-d\TH:i')) }}" required class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block lg:col-span-2"><span class="text-sm font-medium">Short description</span><textarea name="summary" rows="2" class="mt-1 w-full rounded-lg border-slate-300">{{ old('summary', $event?->summary) }}</textarea></label>
    <label class="block lg:col-span-2"><span class="text-sm font-medium">Event description</span><textarea name="description" rows="5" class="mt-1 w-full rounded-lg border-slate-300">{{ old('description', $event?->description) }}</textarea></label>
    <label class="block"><span class="text-sm font-medium">Location</span><input name="location" value="{{ old('location', $event?->location) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Capacity</span><input type="number" min="0" name="capacity" value="{{ old('capacity', $event?->capacity ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Payment tax (%)</span><input type="number" step="0.01" min="0" max="100" name="payment_tax_percentage" value="{{ old('payment_tax_percentage', $event?->payment_tax_percentage ?? 0) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <div class="flex items-end gap-4 text-sm"><input type="hidden" name="allow_promo_code" value="0"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="allow_promo_code" value="1" @checked(old('allow_promo_code', $event?->allow_promo_code ?? true))> Promo code field</label><input type="hidden" name="allow_duplicate_email" value="0"><label class="flex min-h-11 items-center gap-2"><input type="checkbox" name="allow_duplicate_email" value="1" @checked(old('allow_duplicate_email', $event?->allow_duplicate_email ?? false))> Multiple registrations per email</label></div>
    <label class="block"><span class="text-sm font-medium">Sender name</span><input name="sender_name" value="{{ old('sender_name', $event?->sender_name) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Sender email</span><input type="email" name="sender_email" value="{{ old('sender_email', $event?->sender_email) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Registration opens</span><input type="datetime-local" name="registration_opens_at" value="{{ old('registration_opens_at', optional($event?->registration_opens_at)->format('Y-m-d\TH:i')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Registration closes</span><input type="datetime-local" name="registration_closes_at" value="{{ old('registration_closes_at', optional($event?->registration_closes_at)->format('Y-m-d\TH:i')) }}" class="mt-1 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Brand color</span><input type="color" name="brand_color" value="{{ old('brand_color', $event?->brand_color ?? '#047857') }}" class="mt-1 h-11 w-full rounded-lg border-slate-300"></label>
    <label class="block"><span class="text-sm font-medium">Status</span><select name="status_key" class="mt-1 w-full rounded-lg border-slate-300"><option value="draft" @selected(old('status_key', $eventStatus) === 'draft')>Draft</option><option value="published" @selected(old('status_key', $eventStatus) === 'published')>Published</option></select></label>
    <label class="block"><span class="text-sm font-medium">Logo</span><input type="file" name="logo" accept="image/*" class="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2"></label>
    <label class="block"><span class="text-sm font-medium">Banner</span><input type="file" name="banner" accept="image/*" class="mt-1 w-full rounded-lg border border-slate-300 bg-white p-2"></label>
</div>
