@csrf
<div class="grid gap-5 md:grid-cols-2">
    <div><label for="name" class="block text-sm font-medium text-slate-700">Type name</label><input id="name" name="name" value="{{ old('name', $type->name ?? '') }}" required class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="slug" class="block text-sm font-medium text-slate-700">Slug</label><input id="slug" name="slug" value="{{ old('slug', $type->slug ?? '') }}" placeholder="auto-generated when empty" class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div><label for="sort_order" class="block text-sm font-medium text-slate-700">Sort order</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $type->sort_order ?? 0) }}" class="mt-2 block min-h-11 w-full rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"></div>
    <div class="flex items-end gap-5">
        <label class="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $type->is_active ?? true)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Active</label>
        <label class="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="requires_approval" value="1" @checked(old('requires_approval', $type->requires_approval ?? false)) class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-600">Requires approval</label>
    </div>
    <div class="md:col-span-2"><label for="description" class="block text-sm font-medium text-slate-700">Description</label><textarea id="description" name="description" rows="4" class="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">{{ old('description', $type->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800">{{ $button ?? 'Save type' }}</button><a href="{{ route('admin.event-types.index') }}" class="inline-flex min-h-11 items-center rounded-lg border border-slate-300 px-4 text-sm font-semibold hover:bg-slate-50">Cancel</a></div>
