<x-layouts.admin title="Event Types" heading="Event Types" subheading="Define event workflows and approval behavior">
    <section class="rounded-lg border border-slate-200 bg-white shadow-sm">
        <div class="flex flex-col gap-3 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between">
            <form method="GET" class="flex flex-1 flex-col gap-3 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="Search type" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><select name="status" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="">All statuses</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select><button class="min-h-11 rounded-lg border border-slate-300 px-4 text-sm font-semibold hover:bg-slate-50">Filter</button></form>
            <a href="{{ route('admin.event-types.create') }}" class="inline-flex min-h-11 items-center justify-center rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800">New type</a>
        </div>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Type</th><th class="px-5 py-3">Approval</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($types as $type)<tr><td class="px-5 py-4"><a href="{{ route('admin.event-types.show', $type) }}" class="font-semibold hover:text-emerald-700">{{ $type->name }}</a><p class="mt-1 text-slate-500">{{ $type->description }}</p></td><td class="px-5 py-4">{{ $type->requires_approval ? 'Required' : 'Not required' }}</td><td class="px-5 py-4">{{ $type->is_active ? 'Active' : 'Inactive' }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.event-types.edit', $type) }}" class="rounded-lg border border-slate-300 px-3 py-2 font-semibold hover:bg-slate-50">Edit</a><form method="POST" action="{{ route('admin.event-types.destroy', $type) }}" onsubmit="return confirm('Delete this type?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-3 py-2 font-semibold text-red-700 hover:bg-red-50">Delete</button></form></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-8 text-center text-slate-500">No event types found.</td></tr>@endforelse</tbody></table></div>
        <div class="border-t border-slate-200 p-5">{{ $types->links() }}</div>
    </section>
</x-layouts.admin>
