<x-layouts.admin title="Event Detail" heading="{{ $event->title }}" subheading="Event detail, sessions, files, and publication status">
    <div class="grid gap-6 xl:grid-cols-[1fr_320px]">
        <section class="space-y-6">
            <div class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
                @if($event->banner_path)<img src="{{ asset('storage/'.$event->banner_path) }}" alt="{{ $event->title }} banner" class="mb-5 aspect-[16/5] w-full rounded-lg object-cover">@endif
                <dl class="grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Category</dt><dd>{{ $event->category?->name }}</dd></div><div><dt class="text-sm text-slate-500">Type</dt><dd>{{ $event->type?->name }}</dd></div><div><dt class="text-sm text-slate-500">Venue</dt><dd>{{ $event->venue?->name ?? '-' }}</dd></div><div><dt class="text-sm text-slate-500">Capacity</dt><dd>{{ number_format($event->capacity) }}</dd></div><div><dt class="text-sm text-slate-500">Starts</dt><dd>{{ $event->starts_at->format('d M Y, H:i') }}</dd></div><div><dt class="text-sm text-slate-500">Ends</dt><dd>{{ $event->ends_at->format('d M Y, H:i') }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-slate-500">Description</dt><dd class="mt-1 whitespace-pre-line">{{ $event->description ?: 'No description provided.' }}</dd></div></dl>
            </div>
            <div class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Sessions</h2><div class="mt-4 space-y-3">@forelse($event->sessions as $session)<div class="rounded-lg border border-slate-200 p-4"><p class="font-semibold">{{ $session->title }}</p><p class="text-sm text-slate-600">{{ $session->starts_at->format('d M Y H:i') }} - {{ $session->ends_at->format('H:i') }} / {{ $session->venue?->name ?? $event->venue?->name ?? 'No venue' }}</p><p class="mt-2 text-sm text-slate-600">{{ $session->description }}</p></div>@empty<p class="text-sm text-slate-500">No sessions added.</p>@endforelse</div></div>
            <div class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h2 class="font-semibold">Documents</h2><div class="mt-4 space-y-2">@forelse($event->documents as $document)<div class="flex items-center justify-between rounded-lg border border-slate-200 p-3 text-sm"><a href="{{ asset('storage/'.$document->path) }}" class="font-medium text-emerald-700">{{ $document->name }}</a><form method="POST" action="{{ route('admin.events.documents.destroy', [$event,$document]) }}" onsubmit="return confirm('Delete this document?')">@csrf @method('DELETE')<button class="font-semibold text-red-700">Delete</button></form></div>@empty<p class="text-sm text-slate-500">No documents uploaded.</p>@endforelse</div></div>
        </section>
        <aside class="space-y-4"><div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">Lifecycle</p><p class="mt-1 text-lg font-semibold">{{ ucfirst($event->status_key->value) }}</p><p class="mt-3 text-sm text-slate-500">Page: {{ $event->publishedPageVersion ? 'Published' : 'Draft only' }}</p></div><div class="rounded-lg border border-slate-200 bg-white p-5 shadow-sm space-y-3"><a href="{{ route('admin.events.edit',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Edit event</a><a href="{{ route('admin.events.builder.edit',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Page builder</a><a href="{{ route('admin.events.preview',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Preview page</a><a href="{{ route('admin.events.registrations.builder.edit',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Registration builder</a><a href="{{ route('admin.events.registrations.index',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Participants</a><a href="{{ route('admin.events.attendance.index',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Attendance</a><a href="{{ route('admin.events.attendance.scanner',$event) }}" class="flex min-h-11 items-center justify-center rounded-lg border border-slate-300 font-semibold hover:bg-slate-50">Scanner</a><form method="POST" action="{{ route('admin.events.submit',$event) }}">@csrf<button class="min-h-11 w-full rounded-lg bg-blue-700 font-semibold text-white hover:bg-blue-800">Submit event</button></form><form method="POST" action="{{ route('admin.events.publish',$event) }}">@csrf<button class="min-h-11 w-full rounded-lg bg-emerald-700 font-semibold text-white hover:bg-emerald-800">Publish event</button></form></div></aside>
    </div>
</x-layouts.admin>
